
NAME: 'swin_s.NoBP'

DATASET:
  TYPE: 'pedes'
  NAME: 'NoBP'
  TRAIN_SPLIT: 'trainval'
  VAL_SPLIT: 'test'
  ZERO_SHOT: False
  LABEL: 'eval'
  HEIGHT: 256
  WIDTH: 128

RELOAD:
  TYPE: True
  NAME: 'backbone'
  # PTH: 'nobpsb.pth'
  PTH: 'ckpt_max_2024-07-25_14:33:41lastEp.pth'

BACKBONE:
  TYPE: 'swin_s' # swin_t/s/b

CLASSIFIER:
  NAME: 'linear'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'bceloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  CLIP_GRAD: True
  BATCH_SIZE: 64
  OPTIMIZER:
    TYPE: 'adam'
    WEIGHT_DECAY: 0.0
  LR_SCHEDULER:
    TYPE: 'plateau'
    LR_FT: 0.00001
    LR_NEW: 0.00001
  EMA:
    ENABLE: False

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
  TENSORBOARD:
    ENABLE: False