NAME: '.no_bp_shoulderb'

DATASET:
  TYPE: 'pedes'
  NAME: 'NoShoulderNorBackPack_1_1'
  TRAIN_SPLIT: 'trainval'
  VAL_SPLIT: 'test'
  ZERO_SHOT: False
  LABEL: 'eval'
  HEIGHT: 256
  WIDTH: 128

RELOAD:
  TYPE: False
  NAME: 'backbone'

BACKBONE:
  TYPE: 'swin_s' # swin_t/s/bS

CLASSIFIER:
  NAME: 'linear'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'bceloss'
  # TYPE: 'focalloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  CLIP_GRAD: True
  BATCH_SIZE: 64
  OPTIMIZER:
    TYPE: 'adam'
    WEIGHT_DECAY: 0.0
  LR_SCHEDULER:
    TYPE: 'plateau'
    LR_FT: 0.000008
    LR_NEW: 0.000008
  EMA:
    ENABLE: False

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'