NAME: '.ft_after_PA100K'

DATASET:
  TYPE: 'pedes'
  NAME: 'PETA'
  TRAIN_SPLIT: 'trainval'
  VAL_SPLIT: 'test'
  ZERO_SHOT: True
  LABEL: 'eval'
  HEIGHT: 256
  WIDTH: 192

RELOAD:
  TYPE: True
  NAME: 'backbone'
  PTH: 'ckpt_max_2024-07-11_19:17:08.pth'

BACKBONE:
  TYPE: 'swin_s' # swin_t/s/b

CLASSIFIER:
  NAME: 'linear'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'bceloss'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'


TRAIN:
  CLIP_GRAD: True
  MAX_EPOCH: 15
  BATCH_SIZE: 64
  OPTIMIZER:
    TYPE: 'sgd'
    MOMENTUM: 0.8
    WEIGHT_DECAY: 0.0
  LR_SCHEDULER:
    TYPE: 'warmup_cosine'
    # LR_STEP: [10, 15]
    LR_FT: 0.00001
    LR_NEW: 0.00001
  EMA:
    ENABLE: False

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
